/**
 * Contains all the different codes for errors.
 */

/**
 *  Error codes.
 */
export const ERROR_CODES = {
  NOT_DEFINED: 'NOT_DEFINED',
  // INVALID_PARAMS: 'INVALID_PARAMS',
  // NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  // // API ERRORS.
  // API_ONLY_HTTPS: 'API_ONLY_HTTPS',
  // API_METHOD_NOT_FOUND: 'API_METHOD_NOT_FOUND',
  // API_REQUESTS_TOO_OFTEN: 'API_REQUESTS_TOO_OFTEN',
  // API_INVALID_PARAMS: 'API_INVALID_PARAMS',
  // // PROXY ERROR:
  // URL_NOT_DEFINED: 'URL_NOT_DEFINED',

  // SERVICES
  // OTHER_SERVICE_INVALID_RESPONSE: 'OTHER_SERVICE_INVALID_RESPONSE',
  // MERCADO LIBRE
  SERVICE_MERCADO_LIBRE_ITEM_ERROR: 'SERVICE_MERCADO_LIBRE_ITEM_ERROR',
  SERVICE_MERCADO_LIBRE_ITEM_DESCRIPTION_ERROR: 'SERVICE_MERCADO_LIBRE_ITEM_DESCRIPTION_ERROR',
  SERVICE_MERCADO_LIBRE_SEARCH_ERROR: 'SERVICE_MERCADO_LIBRE_SEARCH_ERROR',
  OTHER_SERVICE_ERROR: 'OTHER_SERVICE_ERROR',
} as const;

export default ERROR_CODES;
