/**
 * Contains all the different codes for errors.
 */

/**
 *  Error codes.
 */
export const ERROR_CODES = {
  NOT_DEFINED: 'NOT_DEFINED',

  // API ERRORS.
  API_REQUESTS_TOO_OFTEN: 'API_REQUESTS_TOO_OFTEN',
  API_METHOD_NOT_FOUND: 'API_METHOD_NOT_FOUND',
  API_INVALID_PARAMS: 'API_INVALID_PARAMS',
  API_NOT_AUTHORIZED: 'API_NOT_AUTHORIZED',

  // MERCADO LIBRE
  SERVICE_MERCADO_LIBRE_CATEGORY_ERROR: 'SERVICE_MERCADO_LIBRE_CATEGORY_ERROR',
  SERVICE_MERCADO_LIBRE_ITEM_ERROR: 'SERVICE_MERCADO_LIBRE_ITEM_ERROR',
  SERVICE_MERCADO_LIBRE_ITEM_DESCRIPTION_ERROR: 'SERVICE_MERCADO_LIBRE_ITEM_DESCRIPTION_ERROR',
  SERVICE_MERCADO_LIBRE_SEARCH_ERROR: 'SERVICE_MERCADO_LIBRE_SEARCH_ERROR',
  SERVICE_MERCADO_LIBRE_ITEM_NOT_FOUND: 'SERVICE_MERCADO_LIBRE_ITEM_NOT_FOUND',
  OTHER_SERVICE_ERROR: 'OTHER_SERVICE_ERROR',
} as const;
