
version: '3'

volumes:
  postgres_data:
      driver: local

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=18-alpine
    container_name: frontend
    restart: unless-stopped
    env_file: ./frontend/.env
    ports:
      - "3000:3000"